const db = {
	"Episode I: The Phantom Menace" : {
		"movie_id" : 1,
		"title" : "Episode I: The Phantom Menace",
		"category_name" : "Science Fiction",
		"release_year" : 1999,
		"running_time" : 133,
		"rating_name" : "PG",
		"disc_format_name" : "DVD",
		"number_discs" : 2,
		"viewing_format_name" : "Widescreen",
		"aspect_ratio_name" : "2.35:1",
		"status" : 1,
		"time_stamp" : "2015-09-21"
	},
	"Episode II: Attack of the Clones" : {
		"movie_id" : 2,
		"title" : "Episode II: Attack of the Clones",
		"category_name" : "Science Fiction",
		"release_year" : 2002,
		"running_time" : 142,
		"rating_name" : "PG",
		"disc_format_name" : "DVD",
		"number_discs" : 2,
		"viewing_format_name" : "Widescreen",
		"aspect_ratio_name" : "2.35:1",
		"status" : 1,
		"time_stamp" : "2015-09-21"
	},
	"Episode III: Revenge of the Sith" : {
		"movie_id" : 3,
		"title" : "Episode III: Revenge of the Sith",
		"category_name" : "Science Fiction",
		"release_year" : 2005,
		"running_time" : 140,
		"rating_name" : "PG-13",
		"disc_format_name" : "DVD",
		"number_discs" : 2,
		"viewing_format_name" : "Widescreen",
		"aspect_ratio_name" : "2.35:1",
		"status" : 1,
		"time_stamp" : "2015-09-21"
	},
	"Episode IV: A New Hope" : {
		"movie_id" : 4,
		"title" : "Episode IV: A New Hope",
		"category_name" : "Science Fiction",
		"release_year" : 1977,
		"running_time" : 123,
		"rating_name" : "PG",
		"disc_format_name" : "DVD",
		"number_discs" : 2,
		"viewing_format_name" : "Widescreen",
		"aspect_ratio_name" : "2.35:1",
		"status" : 1,
		"time_stamp" : "2015-09-21"
	},
	"Episode V: The Empire Strikes Back" : {
		"movie_id" : 5,
		"title" : "Episode V: The Empire Strikes Back",
		"category_name" : "Science Fiction",
		"release_year" : 1980,
		"running_time" : 129,
		"rating_name" : "PG",
		"disc_format_name" : "DVD",
		"number_discs" : 2,
		"viewing_format_name" : "Widescreen",
		"aspect_ratio_name" : "2.35:1",
		"status" : 1,
		"time_stamp" : "2015-09-21"
	},
	"Episode VI: Return of the Jedi" : {
		"movie_id" : 6,
		"title" : "Episode VI: Return of the Jedi",
		"category_name" : "Science Fiction",
		"release_year" : 1983,
		"running_time" : 136,
		"rating_name" : "PG",
		"disc_format_name" : "DVD",
		"number_discs" : 2,
		"viewing_format_name" : "Widescreen",
		"aspect_ratio_name" : "2.35:1",
		"status" : 1,
		"time_stamp" : "2015-09-21"
	},
	"Episode VII: The Force Awakens" : {
		"movie_id" : 7,
		"title" : "Episode VII: The Force Awakens",
		"category_name" : "Science Fiction",
		"release_year" : 2015,
		"running_time" : 135,
		"rating_name" : "PG-13",
		"disc_format_name" : "",
		"number_discs" : 1,
		"viewing_format_name" : "Widescreen",
		"aspect_ratio_name" : "2.35:1",
		"status" : 1,
		"time_stamp" : "2015-09-21"
	},
	"Rogue One: A Star Wars Story" : {
		"movie_id" : 8,
		"title" : "Rogue One: A Star Wars Story",
		"category_name" : "Science Fiction",
		"release_year" : 2016,
		"running_time" : 133,
		"rating_name" : "PG-13",
		"disc_format_name" : "",
		"number_discs" : 1,
		"viewing_format_name" : "Widescreen",
		"aspect_ratio_name" : "2.35:1",
		"status" : 1,
		"time_stamp" : "2016-08-17"
	},
	"Episode VIII: The Last Jedi" : {
		"movie_id" : 9,
		"title" : "Star Wars: The Last Jedi",
		"category_name" : "Science Fiction",
		"release_year" : 2017,
		"running_time" : 152,
		"rating_name" : "PG-13",
		"disc_format_name" : "",
		"number_discs" : 1,
		"viewing_format_name" : "Widescreen",
		"aspect_ratio_name" : "2.35:1",
		"status" : 1,
		"time_stamp" : "2018-01-09"
	},
	"Solo: A Star Wars Story" : {
		"movie_id" : 10,
		"title" : "Solo: A Star Wars Story",
		"category_name" : "Science Fiction",
		"release_year" : 2018,
		"running_time" : 135,
		"rating_name" : "PG-13",
		"disc_format_name" : "",
		"number_discs" : 1,
		"viewing_format_name" : "Widescreen",
		"aspect_ratio_name" : "2.35:1",
		"status" : 1,
		"time_stamp" : "2018-11-06"
	}

}

module.exports = db;