package bank.system;

import java.util.ArrayList;
import java.util.Random;

interface BankDriverInterface {
    public void getAccountByCustomerId(long customerId);
    public long createAccount(String customerName, int branchCode, String IFSCCode, String type, double initialMoney);
    public void getAllAccounts();
    public void getBalanceByCustomerId(long customerId);
    public void withdrawal(long customerId, double withdrawalMoney);
    public void deposit(long customerId, double depositMoney);
}

public class BankDriver implements BankDriverInterface {
    private static BankDriver driverInstance;
    private final ArrayList<BankAccount> accounts = new ArrayList<>();


    static {
        System.out.println("=== Bank Driver Initialized ===");
    }

    private BankDriver() {

    }

    public static BankDriver getBankDriverInstance() {
        if(driverInstance != null) return driverInstance;
        driverInstance = new BankDriver();

        return driverInstance;
    }

    /**
     * <p>This method can create a Bank Account of 2 types, SAVING_ACCOUNT through {@link SavingsAccount } or a
     * CURRENT_ACCOUNT through {@link CurrentAccount}.</p>
     * <p>customerId and accountNo fields are used Autogenerated.</p>
     * @param customerName
     * @param branchCode
     * @param IFSCCode
     * @param type
     * @param initialMoney refers to the initial deposit for account creation
     * @return {@code customerId}
     */
    public long createAccount(String customerName, int branchCode, String IFSCCode, String type, double initialMoney) {
        int length = 6;
        int min = (int) Math.pow(10, length - 1);
        int max = (int) Math.pow(10, length) - 1;
        int generatedAccountNo = (min + new Random().nextInt(max - min + 1));
        int generatedCustomerId = (min + new Random().nextInt(max - min + 1));
        BankAccount newAccount = type.equals("SAVINGS_ACCOUNT") ?
                new SavingsAccount(customerName, generatedAccountNo, generatedCustomerId, branchCode, IFSCCode):
                type.equals("CURRENT_ACCOUNT") ?
                        new CurrentAccount(customerName, generatedAccountNo, generatedCustomerId, branchCode, IFSCCode):
                        null;
        accounts.add(newAccount);

        if(newAccount != null) {
            newAccount.setBalance(initialMoney);
            System.out.println("New Account created, the following are the details of your new account");
            newAccount.displayDetails(); // dynamic method dispatch
            return newAccount.getCustomerId();
        } else {
            System.out.println("Error: Bank Account Type mismatch, acceptable types are SAVINGS_ACCOUNT & CURRENT_ACCOUNT");
            return -1;
        }
    }

    @Override
    public void getAccountByCustomerId(long customerId) {
        BankAccount foundAccount = null;
        for (BankAccount account : accounts) {
            if(account.getCustomerId() == customerId) {
                foundAccount = account;
            }
        }
        if(foundAccount != null) {
            foundAccount.displayDetails();
        } else {
            System.out.println("Account with the given customer ID not found");
        }
    }

    @Override
    public void getAllAccounts() {
        System.out.println("***** ALL ACCOUNTS *****");
        for(BankAccount account: accounts) {
            account.displayDetails();
        }
        System.out.println("************************");
    }

    @Override
    public void getBalanceByCustomerId(long customerId) {
        BankAccount foundAccount = null;
        for (BankAccount account : accounts) {
            if(account.getCustomerId() == customerId) {
                foundAccount = account;
            }
        }
        if(foundAccount != null) {
            System.out.printf("%-20s : ₹%.2f%n", "Balance", foundAccount.getBalance());
        } else {
            System.out.println("Account with the given customer ID not found");
        }
    }

    @Override
    public void withdrawal(long customerId, double withdrawalMoney) {
        BankAccount foundAccount = null;
        for (BankAccount account : accounts) {
            if(account.getCustomerId() == customerId) {
                foundAccount = account;
            }
        }
        if(foundAccount == null) {
            System.out.println("Account with the given customer ID not found");
            return;
        }
        double currBalance = foundAccount.getBalance();
        if(withdrawalMoney <= currBalance) {
            foundAccount.setBalance(currBalance - withdrawalMoney);
        }
        System.out.println("Account money withdrawn and balance updated.");
        System.out.printf("%-20s : ₹%.2f%n", "Balance", foundAccount.getBalance());
    }

    @Override
    public void deposit(long customerId, double depositMoney) {
        BankAccount foundAccount = null;
        for (BankAccount account : accounts) {
            if(account.getCustomerId() == customerId) {
                foundAccount = account;
            }
        }
        if(foundAccount == null) {
            System.out.println("Account with the given customer ID not found");
            return;
        }
        double currBalance = foundAccount.getBalance();
        foundAccount.setBalance(currBalance + depositMoney);
        System.out.println("Account money deposited and balance updated.");
        System.out.printf("%-20s : ₹%.2f%n", "Balance", foundAccount.getBalance());
    }

}
